apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "injecto.fullname" . }}
  labels:
    {{- include "injecto.labels" . | nindent 4 }}
data:
  # Injecto configuration
  api.host: {{ .Values.injecto.api.host | quote }}
  api.port: {{ .Values.injecto.api.port | quote }}
  api.debug: {{ .Values.injecto.api.debug | quote }}
